"""Cached suggestion model for storing generated prompts and competitors."""

from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional
from uuid import UUID, uuid4

from sqlalchemy import DateTime, Index, String, Text
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.core.database import Base


class CachedSuggestion(Base):
    """Cached AI-generated suggestions for brands/categories.

    Stores prompts and competitors generated by OpenAI to avoid
    repeated API calls for the same brand/category queries.
    Cache entries expire after 30 days.

    Attributes:
        id: Unique identifier (UUID).
        brand: The brand or category name being queried.
        search_type: Type of search ('brand' or 'category').
        industry: Optional industry context for the search.
        prompts: JSON array of generated prompt suggestions.
        competitors: JSON array of generated competitor suggestions.
        created_at: When the cache entry was created.
        expires_at: When the cache entry expires (30 days from creation).
    """

    __tablename__ = "cached_suggestions"

    # Cache TTL in days
    CACHE_TTL_DAYS = 30

    id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
    )
    brand: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    search_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="brand",
    )
    industry: Mapped[Optional[str]] = mapped_column(
        String(255),
        nullable=True,
    )
    prompts: Mapped[List[str]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )
    competitors: Mapped[List[str]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
    )

    __table_args__ = (
        # Index for fast lookups by brand + search_type + industry
        Index("ix_cached_suggestions_lookup", "brand", "search_type", "industry"),
        # Index for cleaning up expired entries
        Index("ix_cached_suggestions_expires_at", "expires_at"),
    )

    def __repr__(self) -> str:
        """String representation of the cached suggestion."""
        return f"<CachedSuggestion(id={self.id}, brand={self.brand}, search_type={self.search_type})>"

    @property
    def is_expired(self) -> bool:
        """Check if the cache entry has expired."""
        return datetime.utcnow() > self.expires_at.replace(tzinfo=None)

    @classmethod
    def create_with_ttl(
        cls,
        brand: str,
        search_type: str,
        prompts: List[str],
        competitors: List[str],
        industry: Optional[str] = None,
    ) -> "CachedSuggestion":
        """Create a new cache entry with automatic expiry calculation.

        Args:
            brand: The brand or category name.
            search_type: Type of search ('brand' or 'category').
            prompts: List of generated prompts.
            competitors: List of generated competitors.
            industry: Optional industry context.

        Returns:
            A new CachedSuggestion instance with expires_at set.
        """
        now = datetime.utcnow()
        return cls(
            brand=brand.lower().strip(),
            search_type=search_type,
            industry=industry.lower().strip() if industry else None,
            prompts=prompts,
            competitors=competitors,
            created_at=now,
            expires_at=now + timedelta(days=cls.CACHE_TTL_DAYS),
        )
